### ISSUE TITLE
Bug: error building 0.2.1-alpha

### ISSUE THREAD

**Issue by djjuhasz** [nyudlts/go-bagit#7]
We're running go-bagit as an import in our project, and upgrading from 0.2.0-alpha to 0.2.1-alpha causes a build error when we run ValidateBag():

```
# github.com/nyudlts/go-bagit
.../go/pkg/mod/github.com/nyudlts/go-bagit@v0.2.1-alpha/bag.go:153:18: bagit.Serialize undefined (type TagSet has no field or method Serialize)
.../go/pkg/mod/github.com/nyudlts/go-bagit@v0.2.1-alpha/bag.go:168:20: bagInfo.Serialize undefined (type TagSet has no field or method Serialize)
FAIL	github.com/artefactual-sdps/enduro/internal/bagit [build failed]
FAIL
```

**Comment by dmnyu** [comment]
I'll take a look today. This repository is was a exercise in Go that I use for one process in our repository, I'd be very careful using it in any codebase.

**Comment by djjuhasz** [comment]
Importing go-bagit works fine with the 0.3.0-alpha build (testing with go 1.22.3).
